'use client';
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useRef, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuthStore } from '@/store/useAuthStore';
import { getLevelForXP } from '@/lib/constants';
import type { ChatMessageRow, GroupRow } from '@/types/database';

type RosterMember = { user_id:string; display_name:string; avatar_url:string|null; xp:number; streak_current:number; badges:string[]; role:'owner'|'member'; joined_at:string };

export default function CommunityView(){
  const { user }=useAuthStore(); const [groups,setGroups]=useState<GroupRow[]>([]); const [activeId,setActiveId]=useState(''); const [roster,setRoster]=useState<RosterMember[]>([]); const [messages,setMessages]=useState<ChatMessageRow[]>([]); const [hasOlder,setHasOlder]=useState(false); const [mode,setMode]=useState<'members'|'chat'>('members'); const [dialog,setDialog]=useState<'create'|'join'|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const endRef=useRef<HTMLDivElement>(null);
  const active=groups.find(g=>g.id===activeId)??groups[0];

  const loadGroups=useCallback(async()=>{setLoading(true);setError('');const {data,error}=await supabase.rpc('get_my_groups');if(error){setError(schemaMessage(error.message));setGroups([])}else{const next=(data??[]) as GroupRow[];setGroups(next);setActiveId(id=>next.some(g=>g.id===id)?id:next[0]?.id??'')}setLoading(false)},[]);
  const loadGroupData=useCallback(async(id:string)=>{if(!id)return;const [rosterResult,messageResult]=await Promise.all([supabase.rpc('get_group_roster',{target_group_id:id}),supabase.from('chat_messages').select('*').eq('group_id',id).order('created_at',{ascending:false}).limit(50)]);if(rosterResult.error)setError(schemaMessage(rosterResult.error.message));else setRoster((rosterResult.data??[]) as RosterMember[]);if(!messageResult.error){const page=(messageResult.data??[]) as ChatMessageRow[];setMessages([...page].reverse());setHasOlder(page.length===50)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void loadGroups(),0);return()=>window.clearTimeout(timer)},[loadGroups]);
  useEffect(()=>{if(!active?.id)return;const timer=window.setTimeout(()=>void loadGroupData(active.id),0);return()=>window.clearTimeout(timer)},[active?.id,loadGroupData]);
  useEffect(()=>{if(!active?.id)return;const channel=supabase.channel(`group-chat:${active.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages',filter:`group_id=eq.${active.id}`},payload=>{const row=payload.new as ChatMessageRow;setMessages(current=>current.some(item=>item.id===row.id)?current:[...current,row])}).subscribe();return()=>{void supabase.removeChannel(channel)}},[active?.id]);
  useEffect(()=>{if(mode==='chat')endRef.current?.scrollIntoView({behavior:'smooth'})},[messages,mode]);

  const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),2800)};
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const {error}=await supabase.rpc('create_group',{group_name:String(fd.get('name')),group_description:String(fd.get('description'))});if(error)setError(schemaMessage(error.message));else{setDialog(null);flash('Topluluk oluşturuldu');await loadGroups()}};
  const join=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const code=String(new FormData(e.currentTarget).get('code')).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);const {error}=await supabase.rpc('join_group_by_code',{join_code:code});if(error)setError(schemaMessage(error.message));else{setDialog(null);flash('Topluluğa katıldın');await loadGroups()}};
  const leave=async()=>{if(!active||!user||!confirm('Bu topluluktan ayrılmak istiyor musun?'))return;const {error}=await supabase.from('group_members').delete().eq('group_id',active.id).eq('user_id',user.id);if(error)setError(schemaMessage(error.message));else{flash('Topluluktan ayrıldın');await loadGroups()}};
  const remove=async()=>{if(!active||!confirm('Topluluk ve grup mesajları kalıcı olarak silinecek. Devam edilsin mi?'))return;const {error}=await supabase.from('groups').delete().eq('id',active.id);if(error)setError(schemaMessage(error.message));else{flash('Topluluk silindi');await loadGroups()}};
  const send=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!active||!user)return;const form=e.currentTarget;const content=String(new FormData(form).get('message')).trim();if(!content)return;form.reset();const optimistic:ChatMessageRow={id:crypto.randomUUID(),sender_id:user.id,receiver_id:null,group_id:active.id,content,is_read:false,created_at:new Date().toISOString()};setMessages(items=>[...items,optimistic]);const {error}=await supabase.from('chat_messages').insert(optimistic);if(error){setMessages(items=>items.filter(item=>item.id!==optimistic.id));setError(schemaMessage(error.message))}};
  const loadOlder=async()=>{if(!active||!messages[0])return;const {data,error}=await supabase.from('chat_messages').select('*').eq('group_id',active.id).lt('created_at',messages[0].created_at).order('created_at',{ascending:false}).limit(50);if(error){setError(schemaMessage(error.message));return}const page=(data??[]) as ChatMessageRow[];setMessages(current=>[...page].reverse().concat(current));setHasOlder(page.length===50)};

  if(loading)return <div className="loading-panel"><span/><p>Toplulukların hazırlanıyor…</p></div>;
  return <div className="view-stack community-view"><header className="page-heading"><div><span className="eyebrow">BİRLİKTE İSTİKRAR</span><h1>Topluluk</h1><p>Yalnızca seviye, XH ve seri özetini paylaş; kişisel kayıt içeriklerin daima sana özel kalır.</p></div><div className="heading-actions"><button className="ghost-button" onClick={()=>setDialog('join')}>Kodla katıl</button><button className="primary-button" onClick={()=>setDialog('create')}>+ Grup oluştur</button></div></header>
    {(error||notice)&&<div className={error?'inline-alert error':'inline-alert success'}><span>{error?'!':'✓'}</span><p>{error||notice}</p><button onClick={()=>{setError('');setNotice('')}}>×</button></div>}
    {!groups.length?<section className="surface-card community-empty"><div className="community-orbits"><i/><i/><i/><span>◎</span></div><span className="eyebrow">GRUBUM YOK</span><h2>İyi alışkanlıklar, iyi bir çevreyle güçlenir.</h2><p>Yakınların için özel bir topluluk oluştur veya sana gönderilen altı haneli kodla katıl. Günlük, hata ve tefekkür içerikleri paylaşılmaz.</p><div><button className="primary-button" onClick={()=>setDialog('create')}>Grup oluştur</button><button className="ghost-button" onClick={()=>setDialog('join')}>Gruba katıl</button></div></section>:
    <div className="community-layout"><aside className="surface-card group-sidebar"><div className="card-heading"><div><span className="eyebrow">TOPLULUKLARIM</span><h2>{groups.length} grup</h2></div></div><div className="group-switcher">{groups.map(group=><button className={group.id===active?.id?'active':''} key={group.id} onClick={()=>setActiveId(group.id)}><span>{group.name.slice(0,1).toLocaleUpperCase('tr-TR')}</span><div><strong>{group.name}</strong><small>{group.member_count} üye</small></div></button>)}</div><button className="add-group" onClick={()=>setDialog('join')}>+ Başka gruba katıl</button></aside>
      {active&&<main className="surface-card group-main"><header className="group-hero"><div className="group-avatar">{active.name.slice(0,2).toLocaleUpperCase('tr-TR')}</div><div><span className="eyebrow">ÖZEL TOPLULUK</span><h2>{active.name}</h2><p>{active.description||'Birlikte istikrar için sakin bir alan.'}</p></div><div className="group-code"><small>Grup kodu</small><button onClick={async()=>{await navigator.clipboard.writeText(active.group_code);flash('Grup kodu kopyalandı')}}>{active.group_code} <span>⧉</span></button></div></header><div className="group-tabs"><button className={mode==='members'?'active':''} onClick={()=>setMode('members')}>Üyeler <span>{roster.length}</span></button><button className={mode==='chat'?'active':''} onClick={()=>setMode('chat')}>Grup sohbeti</button><div/><button className="danger-link" onClick={active.owner_id===user?.id?remove:leave}>{active.owner_id===user?.id?'Grubu sil':'Ayrıl'}</button></div>
        {mode==='members'?<Roster members={roster}/>:<GroupChat messages={messages} roster={roster} userId={user?.id??''} onSend={send} onLoadOlder={loadOlder} hasOlder={hasOlder} endRef={endRef}/>}</main>}
    </div>}
    {dialog&&<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section className="dialog-card" role="dialog" aria-modal="true"><button className="dialog-close" onClick={()=>setDialog(null)}>×</button><span className="eyebrow">{dialog==='create'?'YENİ TOPLULUK':'DAVET KODU'}</span><h2>{dialog==='create'?'Birlikte gelişmek için alan aç':'Topluluğa katıl'}</h2><p>{dialog==='create'?'Adı ve amacı anlaşılır, sıcak ve özel bir topluluk oluştur.':'Sana gönderilen 6 karakterli kodu gir.'}</p><form onSubmit={dialog==='create'?create:join}>{dialog==='create'?<><label className="field"><span>Grup adı</span><input name="name" minLength={2} maxLength={60} required placeholder="Örn. Sabah Halkası"/></label><label className="field"><span>Kısa açıklama</span><textarea name="description" maxLength={240} rows={3} placeholder="Bu grupta neyi birlikte sürdüreceksiniz?"/></label></>:<label className="field code-field"><span>Grup kodu</span><input name="code" minLength={6} maxLength={6} required placeholder="A1B2C3" autoCapitalize="characters"/></label>}<button className="primary-button" type="submit">{dialog==='create'?'Topluluğu oluştur':'Koda katıl'}</button></form></section></div>}
  </div>;
}

function Roster({members}:{members:RosterMember[]}){if(!members.length)return <div className="empty-state"><i>◎</i><strong>Üyeler yüklenemedi</strong><p>Migration uygulandıktan sonra üye listesi burada görünür.</p></div>;return <div className="roster"><div className="roster-head"><span>Sıra & üye</span><span>Seviye</span><span>Seri</span><span>Toplam XH</span></div>{members.map((m,i)=>{const {level}=getLevelForXP(m.xp);return <article key={m.user_id}><b className={`rank rank-${i+1}`}>{i<3?['Ⅰ','Ⅱ','Ⅲ'][i]:i+1}</b><img src={m.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(m.display_name)}`} alt=""/><div className="member-name"><strong>{m.display_name}</strong><small>{m.role==='owner'?'Kurucu':'Üye'}</small></div><span className="level-badge">{level.icon} {level.name}</span><span className="streak-cell">↗ {m.streak_current}</span><strong className="xp-cell">{m.xp.toLocaleString('tr-TR')} XH</strong></article>})}</div>}

function GroupChat({messages,roster,userId,onSend,onLoadOlder,hasOlder,endRef}:{messages:ChatMessageRow[];roster:RosterMember[];userId:string;onSend:(e:React.FormEvent<HTMLFormElement>)=>void;onLoadOlder:()=>void;hasOlder:boolean;endRef:React.RefObject<HTMLDivElement|null>}){const byId=new Map(roster.map(m=>[m.user_id,m]));return <div className="chat-shell"><div className="message-list">{hasOlder&&<button className="older-messages" onClick={onLoadOlder}>Daha eski mesajları yükle</button>}{!messages.length?<div className="empty-state"><i>◌</i><strong>Sohbet henüz sessiz</strong><p>İlk destek mesajını göndererek alanı başlat.</p></div>:messages.map(message=>{const own=message.sender_id===userId;const member=byId.get(message.sender_id);return <article className={own?'own':''} key={message.id}>{!own&&<img src={member?.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${member?.display_name||'SAH'}`} alt=""/>}<div><small>{own?'Sen':member?.display_name||'Üye'} · {new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(new Date(message.created_at))}</small><p>{message.content}</p></div></article>})}<div ref={endRef}/></div><form className="message-form" onSubmit={onSend}><input name="message" maxLength={2000} autoComplete="off" placeholder="Topluluğa destekleyici bir mesaj yaz…"/><button type="submit">Gönder</button></form></div>}
function schemaMessage(message:string){return message.includes('function')||message.includes('relation')||message.includes('schema cache')?'Topluluk veritabanı migration’ı henüz uygulanmamış. 003_groups_reports.sql dosyasını Supabase’e uygulayın.':message}
