-- SAH World — source-restricted awareness journeys and private engagement tracking.
-- Factual copy is limited to Dijital Hafıza and TRT Haber pages verified on 2026-08-24.

BEGIN;

ALTER TABLE public.regional_awareness_content
  DROP CONSTRAINT IF EXISTS regional_awareness_content_section_check,
  DROP CONSTRAINT IF EXISTS regional_awareness_content_geography_section_key;

ALTER TABLE public.regional_awareness_content
  ADD COLUMN IF NOT EXISTS section_title TEXT,
  ADD COLUMN IF NOT EXISTS content_body TEXT,
  ADD COLUMN IF NOT EXISTS source_name TEXT,
  ADD COLUMN IF NOT EXISTS display_order INTEGER,
  ADD COLUMN IF NOT EXISTS action_cue TEXT;

UPDATE public.regional_awareness_content SET
  section_title = COALESCE(section_title, title),
  content_body = COALESCE(content_body, body),
  source_name = COALESCE(source_name, source_label),
  display_order = COALESCE(display_order, order_index),
  action_cue = COALESCE(action_cue, 'Kaynağı aç, tarihini ve bağlamını kontrol et.');

-- Migration 009 used overview/heritage/today. Replace those draft rows before
-- tightening the section vocabulary to the source-reviewed journey model.
DELETE FROM public.regional_awareness_content;

ALTER TABLE public.regional_awareness_content
  ALTER COLUMN section_title SET NOT NULL,
  ALTER COLUMN content_body SET NOT NULL,
  ALTER COLUMN source_name SET NOT NULL,
  ALTER COLUMN display_order SET NOT NULL,
  ALTER COLUMN action_cue SET NOT NULL,
  ADD CONSTRAINT regional_awareness_content_section_check CHECK (section IN ('history', 'displacement', 'today', 'detention', 'culture', 'solidarity')),
  ADD CONSTRAINT regional_awareness_content_display_order_check CHECK (display_order BETWEEN 1 AND 20);

CREATE TABLE IF NOT EXISTS public.awareness_engagement_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  geography TEXT NOT NULL CHECK (geography IN ('filistin', 'dogu_turkistan')),
  content_id TEXT NOT NULL CHECK (char_length(trim(content_id)) BETWEEN 1 AND 500),
  event_type TEXT NOT NULL CHECK (event_type IN ('section_read', 'action_opened', 'quiz_completed')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, geography, content_id, event_type)
);

CREATE INDEX IF NOT EXISTS awareness_engagement_user_idx ON public.awareness_engagement_log(user_id, created_at DESC);
ALTER TABLE public.awareness_engagement_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS awareness_engagement_select_own ON public.awareness_engagement_log;
DROP POLICY IF EXISTS awareness_engagement_insert_own ON public.awareness_engagement_log;
DROP POLICY IF EXISTS awareness_engagement_update_own ON public.awareness_engagement_log;
CREATE POLICY awareness_engagement_select_own ON public.awareness_engagement_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY awareness_engagement_insert_own ON public.awareness_engagement_log FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY awareness_engagement_update_own ON public.awareness_engagement_log FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS awareness_engagement_updated_at ON public.awareness_engagement_log;
CREATE TRIGGER awareness_engagement_updated_at BEFORE UPDATE ON public.awareness_engagement_log
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.regional_awareness_content
  (geography, section, title, body, source_label, source_url, order_index, section_title, content_body, source_name, display_order, action_cue)
VALUES
('filistin','history','1948: Nekbe ve mülksüzleştirme','TRT Haber’in 15 Mayıs 2024 tarihli dosyası, 14 Mayıs 1948’de İsrail devletinin kurulması sürecinde Filistinlilerin zorunlu göçe maruz bırakılmasını ve 15 Mayıs’ın “Nekbe — Büyük Felaket” olarak anılmasını aktarıyor. Bu anlatı, toprağından edilme ile kuşaklar boyunca taşınan hafızayı birlikte ele alıyor.','TRT Haber · Filistin’in 76 yıldır süren dramı: Nekbe','https://www.trthaber.com/haber/dunya/filistinin-76-yildir-suren-drami-nekbe-857567.html',1,'1948: Nekbe ve mülksüzleştirme','TRT Haber’in 15 Mayıs 2024 tarihli dosyası, 14 Mayıs 1948’de İsrail devletinin kurulması sürecinde Filistinlilerin zorunlu göçe maruz bırakılmasını ve 15 Mayıs’ın “Nekbe — Büyük Felaket” olarak anılmasını aktarıyor. Bu anlatı, toprağından edilme ile kuşaklar boyunca taşınan hafızayı birlikte ele alıyor.','TRT Haber · Filistin’in 76 yıldır süren dramı: Nekbe',1,'Tarihi bir sloganla değil, tarih ve kaynak bağlantısıyla aktar.'),
('filistin','displacement','Sürgün, mültecilik ve geri dönüş iradesi','Dijital Hafıza, Filistinli mültecileri 1948 Nekbesi veya 1967 Haziran Savaşı sonrasında evlerini terk etmek zorunda kalan ve geri dönüşleri engellenen siviller olarak tanımlıyor. Kaynak, farklı ülke ve kamplara dağılan insanların Filistinli kimliğine aidiyetlerini ve geri dönme iradesini sürdürdüğünü vurguluyor.','Dijital Hafıza · Filistinli Mülteciler','https://www.dijitalhafiza.com/kavramlar-sozlugu/filistinli-multeciler',2,'Sürgün, mültecilik ve geri dönüş iradesi','Dijital Hafıza, Filistinli mültecileri 1948 Nekbesi veya 1967 Haziran Savaşı sonrasında evlerini terk etmek zorunda kalan ve geri dönüşleri engellenen siviller olarak tanımlıyor. Kaynak, farklı ülke ve kamplara dağılan insanların Filistinli kimliğine aidiyetlerini ve geri dönme iradesini sürdürdüğünü vurguluyor.','Dijital Hafıza · Filistinli Mülteciler',2,'Mültecileri yalnızca sayı olarak değil; ev, aile ve aidiyet hikâyeleriyle hatırla.'),
('filistin','history','1967 sonrası işgalin genişlemesi','TRT Haber dosyası, İsrail’in 1967’deki Altı Gün Savaşı’nın ardından Batı Şeria ve Gazze Şeridi’ni ele geçirdiğini; sonraki yıllarda Filistin topraklarında yeni yerleşimlerin açıldığını aktarıyor. Bugünü anlamak, 1948 ile 1967 arasındaki sürekliliği birlikte görmeyi gerektiriyor.','TRT Haber · Nekbe dosyası','https://www.trthaber.com/haber/dunya/filistinin-76-yildir-suren-drami-nekbe-857567.html',3,'1967 sonrası işgalin genişlemesi','TRT Haber dosyası, İsrail’in 1967’deki Altı Gün Savaşı’nın ardından Batı Şeria ve Gazze Şeridi’ni ele geçirdiğini; sonraki yıllarda Filistin topraklarında yeni yerleşimlerin açıldığını aktarıyor. Bugünü anlamak, 1948 ile 1967 arasındaki sürekliliği birlikte görmeyi gerektiriyor.','TRT Haber · Nekbe dosyası',3,'Bir güncel haberi paylaşmadan önce olayın 1948 ve 1967 bağlamını kontrol et.'),
('filistin','today','Gazze: tanıkların bugüne verdiği isim','TRT Haber’in 12 Mayıs 2026 tarihli haberinde Gazze’de yaşayan Filistinliler, Ekim 2023’ten beri yaşadıklarını “soykırım” ve 1948’le kıyaslanamayacak ölçekte yeni bir Nekbe olarak nitelendiriyor. Haber; güvenli barınma, su, gıda, sağlık ve eğitim imkânlarından yoksun bırakılan ailelerin doğrudan anlatımlarını aktarıyor. Bu nitelemeler haberdeki tanıkların ve haber çerçevesinin ifadeleridir.','TRT Haber · Gazzelilerin tanıklıkları','https://www.trthaber.com/haber/dunya/filistinliler-yasadigimiz-soykirim-1948deki-nekbe-ile-kiyas-dahi-edilemez-944861.html',4,'Gazze: tanıkların bugüne verdiği isim','TRT Haber’in 12 Mayıs 2026 tarihli haberinde Gazze’de yaşayan Filistinliler, Ekim 2023’ten beri yaşadıklarını “soykırım” ve 1948’le kıyaslanamayacak ölçekte yeni bir Nekbe olarak nitelendiriyor. Haber; güvenli barınma, su, gıda, sağlık ve eğitim imkânlarından yoksun bırakılan ailelerin doğrudan anlatımlarını aktarıyor. Bu nitelemeler haberdeki tanıkların ve haber çerçevesinin ifadeleridir.','TRT Haber · Gazzelilerin tanıklıkları',4,'İnsan onurunu koruyan, grafik görüntü içermeyen tanıklıkları kaynak bağlantısıyla paylaş.'),
('filistin','detention','Mahpuslar ve tutuklular','TRT Haber’in 5 Kasım 2025 tarihli haberinde Filistin Esir İşleri Kurumu Başkanı Raid Ebu Humus, cezaevlerindeki Filistinlilere yönelik sistematik işkence, aç bırakma, tecrit, nakil ve aşağılamadan söz ediyor. Haber, açıklamanın yapıldığı tarihte İsrail hapishanelerinde 10 binden fazla Filistinli bulunduğunu aktarıyor.','TRT Haber · Filistin Esir İşleri Kurumu açıklaması','https://www.trthaber.com/haber/dunya/filistin-esir-isleri-kurumu-baskani-israil-cezaevlerinde-sessiz-soykirim-uyguluyor-924909.html',5,'Mahpuslar ve tutuklular','TRT Haber’in 5 Kasım 2025 tarihli haberinde Filistin Esir İşleri Kurumu Başkanı Raid Ebu Humus, cezaevlerindeki Filistinlilere yönelik sistematik işkence, aç bırakma, tecrit, nakil ve aşağılamadan söz ediyor. Haber, açıklamanın yapıldığı tarihte İsrail hapishanelerinde 10 binden fazla Filistinli bulunduğunu aktarıyor.','TRT Haber · Filistin Esir İşleri Kurumu açıklaması',5,'Mahpuslar hakkında konuşurken iddiayı kimin, hangi tarihte söylediğini görünür kıl.'),
('filistin','solidarity','Sebat, dayanışma ve sivil sorumluluk','TRT Haber’in 25 Şubat 2026 tarihli haberi, Özgürlük ve Sumud Filosu’nun 150’yi aşkın ülkeden katılımcılarla ve 100’ü aşkın gemi ve tekneyle yola çıkacağının duyurulduğunu aktarıyor. Bu örnek, “sumud” adının uluslararası sivil dayanışma ve süreklilik fikriyle birlikte kullanıldığını gösteriyor.','TRT Haber · Özgürlük ve Sumud Filosu','https://www.trthaber.com/haber/dunya/ozgurluk-ve-sumud-filosu-12-nisanda-yeniden-akdenize-acilacak-935510.html',6,'Sebat, dayanışma ve sivil sorumluluk','TRT Haber’in 25 Şubat 2026 tarihli haberi, Özgürlük ve Sumud Filosu’nun 150’yi aşkın ülkeden katılımcılarla ve 100’ü aşkın gemi ve tekneyle yola çıkacağının duyurulduğunu aktarıyor. Bu örnek, “sumud” adının uluslararası sivil dayanışma ve süreklilik fikriyle birlikte kullanıldığını gösteriyor.','TRT Haber · Özgürlük ve Sumud Filosu',6,'Öfkeyi doğrulanabilir bilgiye, düzenli öğrenmeye ve barışçıl dayanışmaya dönüştür.'),
('dogu_turkistan','history','Tarihsel eşik: 1759','Dijital Hafıza’nın zaman tüneli, Mançuların 1755’te Cungarya’yı ele geçirmesinin ardından Tanrı Dağları’nın güneyine ilerlediğini ve 1759’da Doğu Türkistan’ın ilk istilasını gerçekleştirdiğini anlatıyor. Kaynak, dönemin iç çekişmelerinin ortak direnişi zayıflattığını da vurguluyor.','Dijital Hafıza Doğu Türkistan · Mançuların İlk İstilası','https://doguturkistan.dijitalhafiza.com/zaman-tuneli/1759-mancularin-ilk-dogu-turkistan-istilasi',1,'Tarihsel eşik: 1759','Dijital Hafıza’nın zaman tüneli, Mançuların 1755’te Cungarya’yı ele geçirmesinin ardından Tanrı Dağları’nın güneyine ilerlediğini ve 1759’da Doğu Türkistan’ın ilk istilasını gerçekleştirdiğini anlatıyor. Kaynak, dönemin iç çekişmelerinin ortak direnişi zayıflattığını da vurguluyor.','Dijital Hafıza Doğu Türkistan · Mançuların İlk İstilası',1,'Bugünü değerlendirirken coğrafyanın uzun tarihini tek bir döneme indirgeme.'),
('dogu_turkistan','detention','Kitlesel gözaltıların başlangıcı','Dijital Hafıza zaman tüneli, Mart ve Nisan aylarında bölge adalet yetkililerinin güneyde dolaşarak binlerce Uygur, Kazak ve diğer Müslüman azınlığın mahkeme süreci olmadan “yeniden eğitim” kamplarında tutulacağını duyurduğunu aktarıyor.','Dijital Hafıza Doğu Türkistan · Kitlesel Gözaltılar','https://doguturkistan.dijitalhafiza.com/zaman-tuneli/kitlesel-gozaltilarin-baslamasi',2,'Kitlesel gözaltıların başlangıcı','Dijital Hafıza zaman tüneli, Mart ve Nisan aylarında bölge adalet yetkililerinin güneyde dolaşarak binlerce Uygur, Kazak ve diğer Müslüman azınlığın mahkeme süreci olmadan “yeniden eğitim” kamplarında tutulacağını duyurduğunu aktarıyor.','Dijital Hafıza Doğu Türkistan · Kitlesel Gözaltılar',2,'“Kamp” ifadesini kullanırken kaynağın yargı sürecine dair verdiği bağlamı da ekle.'),
('dogu_turkistan','detention','“Mesleki eğitim” adı altındaki kamplar','Dijital Hafıza, Çin makamlarının “Mesleki Eğitim ve Öğretim Merkezi” adını kullandığı yerleri; hukuki süreç olmadan özgürlüğün sistematik biçimde kaldırıldığı, ideolojik baskı ile kültür ve inanca yönelik tahkir iddialarının bulunduğu kapalı yapılar olarak tarif ediyor. Kaynak, kapalı bilgi ortamı nedeniyle kesin sayılara ulaşmanın güç olduğunu ayrıca belirtiyor.','Dijital Hafıza Doğu Türkistan · Toplama Kampları','https://doguturkistan.dijitalhafiza.com/kavramlar-sozlugu/toplama-kamplari',3,'“Mesleki eğitim” adı altındaki kamplar','Dijital Hafıza, Çin makamlarının “Mesleki Eğitim ve Öğretim Merkezi” adını kullandığı yerleri; hukuki süreç olmadan özgürlüğün sistematik biçimde kaldırıldığı, ideolojik baskı ile kültür ve inanca yönelik tahkir iddialarının bulunduğu kapalı yapılar olarak tarif ediyor. Kaynak, kapalı bilgi ortamı nedeniyle kesin sayılara ulaşmanın güç olduğunu ayrıca belirtiyor.','Dijital Hafıza Doğu Türkistan · Toplama Kampları',3,'Doğrulanması güç sayıları tekrar etmek yerine, kaynağın kesinlik sınırını koru.'),
('dogu_turkistan','culture','“Yeniden eğitim” ve inanç baskısı','Dijital Hafıza’nın kavram sayfası, “yeniden eğitim” adı altında Müslüman Uygurların inançlarıyla bağdaşmayan davranışlara zorlandığı uygulamaları aktarıyor. Bu anlatım, kamp politikasını yalnızca gözaltı değil, kimlik ve inanç üzerinde baskı iddiası olarak da ele alıyor.','Dijital Hafıza Doğu Türkistan · Yeniden Eğitim','https://doguturkistan.dijitalhafiza.com/kavramlar-sozlugu/yeniden-egitim',4,'“Yeniden eğitim” ve inanç baskısı','Dijital Hafıza’nın kavram sayfası, “yeniden eğitim” adı altında Müslüman Uygurların inançlarıyla bağdaşmayan davranışlara zorlandığı uygulamaları aktarıyor. Bu anlatım, kamp politikasını yalnızca gözaltı değil, kimlik ve inanç üzerinde baskı iddiası olarak da ele alıyor.','Dijital Hafıza Doğu Türkistan · Yeniden Eğitim',4,'Bir topluluğu yalnız mağduriyetle değil; dil, inanç, sanat ve gündelik hayatıyla da tanı.'),
('dogu_turkistan','culture','Kültürel ve dinî kimliğe yönelik baskı','TRT Haber’in 9 Şubat 2019 tarihli haberinde Türkiye Dışişleri Bakanlığı Sözcüsü, Ekim 2017’de ilan edilen “Tüm Dinlerin ve İnançların Çinlileştirilmesi” siyasetini Uygurların ve diğer Müslüman toplulukların etnik, dinî ve kültürel kimliklerinin tasfiyesine yönelik bir adım olarak nitelendiriyor ve kampların kapatılması çağrısı yapıyor.','TRT Haber · Dışişleri Bakanlığı açıklaması','https://www.trthaber.com/haber/gundem/cin-makamlarini-toplama-kamplarini-kapatmaya-davet-ediyoruz-404380.html',5,'Kültürel ve dinî kimliğe yönelik baskı','TRT Haber’in 9 Şubat 2019 tarihli haberinde Türkiye Dışişleri Bakanlığı Sözcüsü, Ekim 2017’de ilan edilen “Tüm Dinlerin ve İnançların Çinlileştirilmesi” siyasetini Uygurların ve diğer Müslüman toplulukların etnik, dinî ve kültürel kimliklerinin tasfiyesine yönelik bir adım olarak nitelendiriyor ve kampların kapatılması çağrısı yapıyor.','TRT Haber · Dışişleri Bakanlığı açıklaması',5,'Kültürel baskıyı anlatırken açıklamanın sahibini ve tarihini açıkça belirt.'),
('dogu_turkistan','today','Uluslararası belgeleme ve şeffaflık ihtiyacı','TRT Haber’in 29 Aralık 2022 tarihli haberinde dönemin Dışişleri Bakanı Mevlüt Çavuşoğlu, BM İnsan Hakları Komiserinin görevden ayrılırken yayımladığı raporun ihlalleri ortaya koyduğunu söylüyor; bağımsız bir insani heyetin bölgeye erişebilmesi ve şeffaf inceleme yapılması gerektiğini vurguluyor.','TRT Haber · BM raporu ve şeffaf inceleme açıklaması','https://www.trthaber.com/haber/gundem/bakan-cavusoglu-rejim-de-teror-tehdidinin-farkinda-ortak-mucadele-olabilir-734259.html',6,'Uluslararası belgeleme ve şeffaflık ihtiyacı','TRT Haber’in 29 Aralık 2022 tarihli haberinde dönemin Dışişleri Bakanı Mevlüt Çavuşoğlu, BM İnsan Hakları Komiserinin görevden ayrılırken yayımladığı raporun ihlalleri ortaya koyduğunu söylüyor; bağımsız bir insani heyetin bölgeye erişebilmesi ve şeffaf inceleme yapılması gerektiğini vurguluyor.','TRT Haber · BM raporu ve şeffaf inceleme açıklaması',6,'Sosyal medya özetleri yerine erişilebilir raporları ve açık kaynak zincirini takip et.');

DELETE FROM public.awareness_quiz_questions;
INSERT INTO public.awareness_quiz_questions
  (geography, order_index, question_text, option_a, option_b, option_c, option_d, correct_option, explanation_text, source_url)
VALUES
('filistin',1,'TRT Haber dosyasına göre Nekbe hangi Türkçe ifadeyle açıklanır?','Büyük Felaket','Uzun Yolculuk','Sessiz Bahar','Yeni Başlangıç','A','TRT Haber, Nekbe ifadesini “Büyük Felaket” olarak açıklar.','https://www.trthaber.com/haber/dunya/filistinin-76-yildir-suren-drami-nekbe-857567.html'),
('filistin',2,'TRT Haber’e göre Nekbe hangi tarihte anılır?','15 Mayıs','1 Ocak','29 Ekim','10 Aralık','A','İsrail devletinin 14 Mayıs 1948’de kurulmasının ertesi günü olan 15 Mayıs, Nekbe olarak anılır.','https://www.trthaber.com/haber/dunya/filistinin-76-yildir-suren-drami-nekbe-857567.html'),
('filistin',3,'1967’deki savaşın ardından İsrail’in ele geçirdiği iki bölge hangileridir?','Batı Şeria ve Gazze Şeridi','Ürdün ve Lübnan','Kahire ve Şam','Kıbrıs ve Girit','A','TRT Haber dosyası 1967’nin ardından Batı Şeria ve Gazze Şeridi’nin ele geçirildiğini aktarır.','https://www.trthaber.com/haber/dunya/filistinin-76-yildir-suren-drami-nekbe-857567.html'),
('filistin',4,'Dijital Hafıza, Filistinli mültecileri hangi iki tarihsel eşikle ilişkilendirir?','1948 Nekbesi ve 1967 Haziran Savaşı','1914 ve 1918','1973 ve 1974','2001 ve 2005','A','Kavram sayfası, zorunlu göçü 1948 Nekbesi ve 1967 Haziran Savaşı sonrasıyla ilişkilendirir.','https://www.dijitalhafiza.com/kavramlar-sozlugu/filistinli-multeciler'),
('filistin',5,'Dijital Hafıza’ya göre Filistinli mülteciler hangi iradeyi sürdürmektedir?','Topraklarına dönme iradesini','Kimliklerini unutma iradesini','Kayıtları silme iradesini','Tarihi kapatma iradesini','A','Kaynak, mültecilerin geri dönüş iradesini ve Filistinli kimliğine aidiyetini koruduğunu vurgular.','https://www.dijitalhafiza.com/kavramlar-sozlugu/filistinli-multeciler'),
('filistin',6,'12 Mayıs 2026 tarihli TRT Haber, bugünkü Gazze’yi en çok kimlerin anlatımıyla aktarır?','Gazze’de yaşayan Filistinlilerin','Spor yorumcularının','Turizm şirketlerinin','Teknoloji yöneticilerinin','A','Haber, çadırlarda yaşayan Gazze sakinlerinin doğrudan tanıklıklarına yer verir.','https://www.trthaber.com/haber/dunya/filistinliler-yasadigimiz-soykirim-1948deki-nekbe-ile-kiyas-dahi-edilemez-944861.html'),
('filistin',7,'TRT Haber’de cezaevi koşullarına ilişkin açıklamayı yapan kurum hangisidir?','Filistin Esir İşleri Kurumu','Dünya Meteoroloji Örgütü','Uluslararası Olimpiyat Komitesi','Avrupa Uzay Ajansı','A','Açıklama Filistin Esir İşleri Kurumu Başkanı Raid Ebu Humus’a aittir.','https://www.trthaber.com/haber/dunya/filistin-esir-isleri-kurumu-baskani-israil-cezaevlerinde-sessiz-soykirim-uyguluyor-924909.html'),
('filistin',8,'Raid Ebu Humus’un aktarılan açıklamasında mahpuslara yönelik uygulamalardan biri hangisidir?','Tecrit','Burs programı','Ücretsiz seyahat','Spor kampı','A','TRT Haber, açıklamada sistematik işkence, aç bırakma, tecrit, nakil ve aşağılamanın sayıldığını aktarır.','https://www.trthaber.com/haber/dunya/filistin-esir-isleri-kurumu-baskani-israil-cezaevlerinde-sessiz-soykirim-uyguluyor-924909.html'),
('filistin',9,'Özgürlük ve Sumud Filosu için duyurulan hareket tarihi hangisidir?','12 Nisan 2026','15 Mayıs 2024','1 Ocak 2027','10 Aralık 2025','A','TRT Haber, filonun 12 Nisan 2026’da İspanya’dan açılacağının duyurulduğunu bildirir.','https://www.trthaber.com/haber/dunya/ozgurluk-ve-sumud-filosu-12-nisanda-yeniden-akdenize-acilacak-935510.html'),
('filistin',10,'TRT Haber’e göre Özgürlük ve Sumud Filosu kaçtan fazla ülkeden katılımcı hedefliyordu?','150’den fazla','10’dan fazla','25’ten fazla','50’den fazla','A','Haberde 150’yi aşkın ülkeden binlerce katılımcı ifadesi yer alır.','https://www.trthaber.com/haber/dunya/ozgurluk-ve-sumud-filosu-12-nisanda-yeniden-akdenize-acilacak-935510.html'),
('dogu_turkistan',1,'Dijital Hafıza zaman tüneline göre Mançuların ilk Doğu Türkistan istilası hangi yılda gerçekleşti?','1759','1453','1918','2001','A','Zaman tüneli, ilk istilayı 1759 yılına tarihler.','https://doguturkistan.dijitalhafiza.com/zaman-tuneli/1759-mancularin-ilk-dogu-turkistan-istilasi'),
('dogu_turkistan',2,'Mançular 1755’te hangi bölgeyi ele geçirdikten sonra güneye ilerledi?','Cungarya','Anadolu','Balkanlar','Hicaz','A','Kaynak, Mançuların 1755’te Cungarya’yı ele geçirdiğini anlatır.','https://doguturkistan.dijitalhafiza.com/zaman-tuneli/1759-mancularin-ilk-dogu-turkistan-istilasi'),
('dogu_turkistan',3,'Kitlesel gözaltı duyurularının yapıldığı aylar hangileridir?','Mart ve Nisan','Ocak ve Şubat','Temmuz ve Ağustos','Kasım ve Aralık','A','Dijital Hafıza zaman tüneli, yetkililerin Mart ve Nisan aylarında bölgeyi dolaştığını aktarır.','https://doguturkistan.dijitalhafiza.com/zaman-tuneli/kitlesel-gozaltilarin-baslamasi'),
('dogu_turkistan',4,'Kaynağa göre gözaltı duyurularında hangi topluluklar birlikte anılır?','Uygurlar, Kazaklar ve diğer Müslüman azınlıklar','Yalnız turistler','Yalnız sporcular','Yalnız diplomatlar','A','Zaman tüneli Uygur, Kazak ve diğer Müslüman azınlıkları birlikte sayar.','https://doguturkistan.dijitalhafiza.com/zaman-tuneli/kitlesel-gozaltilarin-baslamasi'),
('dogu_turkistan',5,'Dijital Hafıza’ya göre kamplar için kullanılan resmî adlandırma hangisidir?','Mesleki Eğitim ve Öğretim Merkezi','Açık Üniversite Kampüsü','Kültür ve Spor Köyü','Turizm Eğitim Parkı','A','Kavram sayfası, Çin makamlarının “Mesleki Eğitim ve Öğretim Merkezi” adını kullandığını aktarır.','https://doguturkistan.dijitalhafiza.com/kavramlar-sozlugu/toplama-kamplari'),
('dogu_turkistan',6,'Dijital Hafıza, kamp verilerinde kesinliğin neden sınırlı olduğunu söyler?','Gizlilik ve kapalılık politikaları','Mevsim değişikliği','Harita ölçeği','Dilbilgisi farkı','A','Kaynak, gizlilik ve kapalılık nedeniyle net bilgilere ulaşmanın güç olduğunu açıkça belirtir.','https://doguturkistan.dijitalhafiza.com/kavramlar-sozlugu/toplama-kamplari'),
('dogu_turkistan',7,'“Yeniden eğitim” kavram sayfası baskıyı hangi alanla da ilişkilendirir?','Dinî inanç ve gündelik pratiklerle','Yalnız trafik eğitimiyle','Yalnız sporla','Yalnız hava durumuyla','A','Kaynak, Müslüman Uygurların inançlarıyla bağdaşmayan davranışlara zorlandığı iddialarını aktarır.','https://doguturkistan.dijitalhafiza.com/kavramlar-sozlugu/yeniden-egitim'),
('dogu_turkistan',8,'TRT Haber’de aktarılan “Tüm Dinlerin ve İnançların Çinlileştirilmesi” siyaseti hangi yıl ilan edildi?','2017','1990','2005','2024','A','Dışişleri Bakanlığı açıklaması, bu siyasetin Ekim 2017’de ilan edildiğini belirtir.','https://www.trthaber.com/haber/gundem/cin-makamlarini-toplama-kamplarini-kapatmaya-davet-ediyoruz-404380.html'),
('dogu_turkistan',9,'TRT Haber’e göre Türkiye Dışişleri Bakanlığı Çin makamlarına hangi çağrıyı yaptı?','Kampları kapatma çağrısı','Yeni kamp açma çağrısı','Spor turnuvası çağrısı','Ticaret fuarı çağrısı','A','Haberde Uygurların temel insan haklarına saygı gösterilmesi ve kampların kapatılması çağrısı aktarılır.','https://www.trthaber.com/haber/gundem/cin-makamlarini-toplama-kamplarini-kapatmaya-davet-ediyoruz-404380.html'),
('dogu_turkistan',10,'TRT Haber’de dönemin Dışişleri Bakanı bölge için hangi yöntemi savunuyordu?','Şeffaf inceleme ve insani heyet erişimi','Kaynağı belirsiz paylaşımlar','Tarihsiz söylentiler','Kapalı sosyal medya grupları','A','Haberde şeffaf iş birliği ve bağımsız bir insani heyetin bölgeyi inceleyebilmesi gerektiği vurgulanır.','https://www.trthaber.com/haber/gundem/bakan-cavusoglu-rejim-de-teror-tehdidinin-farkinda-ortak-mucadele-olabilir-734259.html');

COMMENT ON TABLE public.regional_awareness_content IS 'Source-restricted, user-visible awareness summaries. Every factual block carries one verified source URL.';
COMMENT ON TABLE public.awareness_engagement_log IS 'Private per-user reading, action and quiz engagement; protected by own-row RLS.';

COMMIT;
